apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: CronJobTemplate
  namespace: default
spec:
  schedule: "* * * *"
  jobTemplate:
    spec:
      template:
        spec:
            automountServiceAccountToken: true
